# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Triplebit
tagline:          'Public Privacy Infrastructure'
description:      'A Minnesota, USA-based nonprofit internet service provider promoting privacy and human rights worldwide.'
url:              https://www.triplebit.org

author:
  name:           'Jonah Aragon'
  url:            https://twitter.com/jonaharagon

paginate:         5
paginate_path:    '/blog/page:num/'

collections:
  history:
    output: false

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/triplebit

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
