site_name: Triplebit
site_url: https://www.triplebit.org/
edit_uri: https://github.com/triplebit/triplebit.org/edit/main/docs/

theme:
  name: material
  favicon: public/triplebit-logo-square.svg
  logo: public/triplebit-logo-square-white.svg
  custom_dir: theme
  font:
    text: Montserrat
  palette:
    primary: custom
    accent: cyan
  features:
    - navigation.sections
    - navigation.tabs
    - content.action.edit

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://mstdn.plus/@triplebit

markdown_extensions:
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - privacy: {}

exclude_docs: |
  !.well-known

extra_css:
  - stylesheets/extra.css

watch:
  - theme

nav:
  - About:
    - index.md
    - history.md
    - people.md
    - donate.md
  - Tor Relays:
    - relays.md
    - legal.md
  - Network Operations:
    - peering.md
  - Transparency:
    - transparency.md
  - Shop: https://shop.jonaharagon.com/collections/triplebit
